### ISSUE TITLE
実行時の応答がメッセージの spoiler を貫通する

### ISSUE THREAD

**Issue by Nanai10a** [approvers/pindome-chan#45]
## 問題箇所

Application Command の実行時に, 例えば対象の message content `||hidden text||` を `||hidden t` までで切り取ってしまった場合, spoiler をかけた冒頭部分の spoiler が外れてしまい, 且つ応答が ephemeral でないため内容が不用意に晒されてしまう.

## 解決方法

先に挙げた例の場合, `||hidden t` という切り取りを更に `||hidden||` と書き換えてしまえば良いと考えている.

## その他

owner はどうお考えですか？ちなみに私個人としてはこの挙動のままでも良い気がしますが, しかし不用意な spoiler の解除は場合によっては不愉快な挙動となる可能性も考えられ, 一概には言いづらいと考えています.

**Comment by MikuroXina** [comment]
単純な切り取り処理の部分を工夫して, spoiler の区間内に切り取りの端点が存在する場合は提案のような処理を施してみようと思います. ご提案ありがとうございます.

**Comment by MikuroXina** [comment]
#46 で対応しました.

**Comment by Nanai10a** [comment]
本番環境で期待した挙動を確認しました. 対応ありがとうございました！
