### ISSUE TITLE
画像をピン留めすることが出来ない

### ISSUE THREAD

**Issue by m2en** [approvers/pindome-chan#9]
![image](https://user-images.githubusercontent.com/82575685/139289027-afa2cdff-d4db-47d5-b271-5353390c4bb0.png)

ピン留め完了のメッセージが送信されるが、 `#ピン留めちゃんの巣窟` にWebhookが送信されていない

**Comment by MikuroXina** [comment]
ボットからメッセージの画像データを取得できない (URL をそのまま `fetch` しても `403 Forbidden` になる) ので対応策を模索中です.

**Comment by MikuroXina** [comment]
[Discord チュートリアル](https://discord.com/developers/docs/tutorials/hosting-on-cloudflare-workers#creating-your-cloudflare-worker) によると, 非エフェメラル CDN の画像にアクセスできない仕様になっているようです.

> When using Cloudflare Workers, your app won't be able to access non-ephemeral CDN media. For example, trying to fetch an image like https://cdn.discordapp.com/attachments/1234/56789/my_image.png would result in a 403 error. Cloudflare Workers are still able to access ephemeral CDN media.

**Comment by MikuroXina** [comment]
暫定的に, 非エフェメラル CDN の画像は取り除いたうえでピン留めする仕様にしました. 今後 Discord 側で対応や仕様変更があれば, 追って改善する予定です.
